export const config: Config = {
  targetDir: "/Users/ivov/Development/n8n/packages/nodes-base/nodes",
  sortLogs: "lineNumber",
  showDetails: true,
  logLevelColors: {
    error: "",
    warning: "",
    info: "",
  },
  truncation: {
    enabled: true,
    charLimit: 60,
  },
  logLevelsEnabled: {
    error: true,
    warning: true,
    info: true,
  },
  lintAreasEnabled: {
    default: true,
    displayName: true,
    limit: true,
    miscellaneous: true,
    name: true,
    nodeDescription: true,
    options: true,
    paramDescription: true,
  },
  lintIssuesEnabled: {
    alphabetization: true,
    casing: true,
    icon: true,
    location: true,
    missing: true,
    naming: true,
    punctuation: true,
    unneeded: true,
    whitespace: true,
    wording: true,
    wrong: true,
  },
};
