export const LINTINGS: {
  [key in string]: Linting;
} = {
  WRONG_DEFAULT_FOR_STRING_TYPE_PARAM: {
    lintAreas: ["default"],
    lintIssue: "wrong",
    message: "Non-string default for string-type param",
    enabled: true,
    logLevel: "error",
  },
  WRONG_DEFAULT_FOR_NUMBER_TYPE_PARAM: {
    lintAreas: ["default"],
    lintIssue: "wrong",
    message: "Non-numeric default for number-type param",
    enabled: true,
    logLevel: "error",
  },
  WRONG_DEFAULT_FOR_BOOLEAN_TYPE_PARAM: {
    lintAreas: ["default"],
    lintIssue: "wrong",
    message: "Non-boolean default for boolean-type param",
    enabled: true,
    logLevel: "error",
  },
  WRONG_DEFAULT_FOR_COLLECTION_TYPE_PARAM: {
    lintAreas: ["default"],
    lintIssue: "wrong",
    message: "Non-object default for collection-type param",
    enabled: true,
    logLevel: "error",
  },
  WRONG_DEFAULT_FOR_MULTIOPTIONS_TYPE_PARAM: {
    lintAreas: ["default"],
    lintIssue: "wrong",
    message: "Non-array default for multiOptions-type param",
    enabled: true,
    logLevel: "error",
  },
  WRONG_DEFAULT_FOR_OPTIONS_TYPE_PARAM: {
    lintAreas: ["default"],
    lintIssue: "wrong",
    message: "Non-option default for options-type param",
    enabled: true,
    logLevel: "error",
  },
  DEFAULT_MISSING: {
    lintAreas: ["default"],
    lintIssue: "missing",
    message: "Default value missing for param",
    enabled: true,
    logLevel: "error",
  },

  DISPLAYNAME_WITH_MISCASED_ID: {
    lintAreas: ["displayName"],
    lintIssue: "casing",
    message: "Miscased `ID` in `displayName` property",
    enabled: true,
    logLevel: "error",
  },
  DISPLAYNAME_WITH_NO_TITLECASE: {
    lintAreas: ["displayName"],
    lintIssue: "casing",
    message: "No title case in `displayName` property",
    enabled: true,
    logLevel: "error",
  },

  LIMIT_WITHOUT_TYPE_OPTIONS: {
    lintAreas: ["limit"],
    lintIssue: "missing",
    message: "Limit param without `typeOptions`",
    enabled: true,
    logLevel: "error",
  },
  LIMIT_WITH_MIN_VALUE_LOWER_THAN_ONE: {
    lintAreas: ["limit"],
    lintIssue: "missing",
    message: "Limit param with min value lower than one",
    enabled: true,
    logLevel: "error",
  },
  WRONG_DEFAULT_FOR_LIMIT_PARAM: {
    lintAreas: ["limit", "default"],
    lintIssue: "wrong",
    message: "Non-50 default for limit param",
    enabled: true,
    logLevel: "error",
  },
  NON_STANDARD_LIMIT_DESCRIPTION: {
    lintAreas: ["limit"],
    lintIssue: "wording",
    message: "Non-standard description for limit param",
    enabled: true,
    logLevel: "info",
  },

  REQUIRED_FALSE: {
    lintAreas: ["miscellaneous"],
    lintIssue: "unneeded",
    message: "Unneeded `required: false` in param property",
    enabled: true,
    logLevel: "warning",
  },
  PUSH_APPLY: {
    lintAreas: ["miscellaneous"],
    lintIssue: "unneeded",
    message:
      "Unneeded `arr.push.apply(arr, arg)` instead of `arr.push(...arg)`",
    enabled: true,
    logLevel: "warning",
  },
  NON_STANDARD_RETURNALL_DESCRIPTION: {
    lintAreas: ["miscellaneous"],
    lintIssue: "wording",
    message: "Non-standard description for returnAll param",
    enabled: true,
    logLevel: "info",
  },

  NAME_WITH_MISCASED_ID: {
    lintAreas: ["name"],
    lintIssue: "casing",
    message: "Miscased `id` in `name` property",
    enabled: true,
    logLevel: "error",
  },
  NAME_WITH_NO_CAMELCASE: {
    lintAreas: ["name"],
    lintIssue: "casing",
    message: "No camel case in `name` property",
    enabled: true,
    logLevel: "error",
  },
  AUTHENTICATION_PROPERTY_NOT_IN_CREDENTIALS: {
    lintAreas: ["name"],
    lintIssue: "location",
    message: "Authentication param should be in credentials",
    enabled: true,
    logLevel: "info",
  },

  PNG_ICON_IN_NODE_DESCRIPTION: {
    lintAreas: ["nodeDescription"],
    lintIssue: "icon",
    message: "Icon is PNG instead of SVG in node description",
    enabled: true,
    logLevel: "error",
  },
  SUBTITLE_MISSING_IN_NODE_DESCRIPTION: {
    lintAreas: ["nodeDescription"],
    lintIssue: "missing",
    message: "Missing `subtitle` in node description",
    enabled: true,
    logLevel: "error",
  },
  NON_STANDARD_SUBTITLE: {
    lintAreas: ["nodeDescription"],
    lintIssue: "wording",
    message: "Non-standard `subtitle` in node description",
    enabled: true,
    logLevel: "info",
  },
  DISPLAYNAME_NOT_ENDING_WITH_TRIGGER_IN_NODE_DESCRIPTION: {
    lintAreas: ["nodeDescription", "displayName"],
    lintIssue: "naming",
    message:
      "Display name in trigger node description not ending with 'Trigger'",
    enabled: true,
    logLevel: "error",
  },
  NAME_NOT_ENDING_WITH_TRIGGER_IN_NODE_DESCRIPTION: {
    lintAreas: ["nodeDescription", "name"],
    lintIssue: "naming",
    message: "Name in trigger node description not ending with 'trigger'",
    enabled: true,
    logLevel: "error",
  },

  NON_ALPHABETIZED_OPTIONS_IN_OPTIONS_TYPE_PARAM: {
    lintAreas: ["options"],
    lintIssue: "alphabetization",
    message: "Non-alphabetized `options` in `options`-type param",
    enabled: true,
    logLevel: "error",
  },
  NON_ALPHABETIZED_OPTIONS_IN_MULTIOPTIONS_TYPE_PARAM: {
    lintAreas: ["options"],
    lintIssue: "alphabetization",
    message: "Non-alphabetized `options` in `multiOptions`-type param",
    enabled: true,
    logLevel: "error",
  },
  NON_ALPHABETIZED_OPTIONS_IN_COLLECTION_TYPE_PARAM: {
    lintAreas: ["options"],
    lintIssue: "alphabetization",
    message: "Non-alphabetized `options` in `collection`-type param",
    enabled: true,
    logLevel: "error",
  },
  NON_ALPHABETIZED_VALUES_IN_FIXED_COLLECTION_TYPE_PARAM: {
    lintAreas: ["options"], // strictly `values`, but functionally same as `options`
    lintIssue: "alphabetization",
    message: "Non-alphabetized `values` in `fixedCollection`-type param",
    enabled: true,
    logLevel: "error",
  },
  NO_TITLECASE_IN_FIXED_COLLECTION_VALUE_DISPLAY_NAME: {
    lintAreas: ["options", "displayName"], // strictly `values`, but functionally same as `options`
    lintIssue: "casing",
    message: "No title case in `fixedCollection` value display name",
    enabled: true,
    logLevel: "error",
  },
  NO_TITLECASE_IN_OPTIONS_NAME: {
    lintAreas: ["options"],
    lintIssue: "casing",
    message: "No title case in `options` name",
    enabled: true,
    logLevel: "error",
  },
  NO_CAMELCASE_IN_OPTIONS_VALUE: {
    lintAreas: ["options"],
    lintIssue: "casing",
    message: "No camel case in `options` value",
    enabled: true,
    logLevel: "error",
  },

  NON_STANDARD_NAME_FOR_UPSERT_OPTION: {
    lintAreas: ["options"],
    lintIssue: "wording",
    message: "Name of option for upsert is misworded",
    enabled: true,
    logLevel: "error",
    details: "The upsert option must be worded: 'Create or Update'",
  },

  NON_STANDARD_DESCRIPTION_FOR_UPSERT_OPTION: {
    lintAreas: ["options"],
    lintIssue: "wording",
    message: "Description of option for upsert is misworded",
    enabled: true,
    logLevel: "error",
    details:
      "The upsert option description must be worded: 'Create a new record, or update the current one if it already exists (upsert)'",
  },

  PARAM_DESCRIPTION_WITH_UNCAPITALIZED_INITIAL: {
    lintAreas: ["paramDescription"],
    lintIssue: "casing",
    message: "Non-capital initial letter in param description",
    enabled: true,
    logLevel: "error",
  },
  PARAM_DESCRIPTION_WITH_EXCESS_FINAL_PERIOD: {
    lintAreas: ["paramDescription"],
    lintIssue: "punctuation",
    message: "Excess final period in param description",
    enabled: true,
    logLevel: "error",
  },
  PARAM_DESCRIPTION_MISSING_WHERE_REQUIRED: {
    lintAreas: ["paramDescription"],
    lintIssue: "missing",
    message: "Param description is missing where it is required",
    enabled: true,
    logLevel: "error",
    details:
      "All param and options are required except resource option, credentials option, and defaults option",
  },
  PARAM_DESCRIPTION_MISSING_WHERE_OPTIONAL: {
    lintAreas: ["paramDescription"],
    lintIssue: "missing",
    message: "Param description is missing where it is optional",
    enabled: true,
    logLevel: "info",
    details:
      "The only pptional descriptions are resource option, credentials option, and defaults option",
  },
  PARAM_DESCRIPTION_WITH_UNNEEDED_BACKTICKS: {
    lintAreas: ["paramDescription"],
    lintIssue: "unneeded",
    message: "Param description has unneeded backticks",
    enabled: true,
    logLevel: "warning",
  },
  ANCHOR_LINK_WITH_TARGET_BLANK_MISSING: {
    lintAreas: ["paramDescription"],
    lintIssue: "missing",
    message: 'Anchor link has no attribute target="_blank"',
    enabled: true,
    logLevel: "error",
  },
  PARAM_DESCRIPTION_AS_EMPTY_STRING: {
    lintAreas: ["paramDescription"],
    lintIssue: "missing",
    message: "Param description is an empty string",
    enabled: true,
    logLevel: "error",
  },
  PARAM_DESCRIPTION_UNTRIMMED: {
    lintAreas: ["paramDescription"],
    lintIssue: "whitespace",
    message: "Param description is untrimmed",
    enabled: true,
    logLevel: "warning",
  },
  BOOLEAN_DESCRIPTION_NOT_STARTING_WITH_WHETHER: {
    lintAreas: ["paramDescription"],
    lintIssue: "wording",
    message: "Boolean param description not starting with 'Whether'",
    enabled: true,
    logLevel: "warning",
  },
  WEAK_PARAM_DESCRIPTION: {
    lintAreas: ["paramDescription"],
    lintIssue: "wording",
    message: "Weak param description to be improved or omitted",
    enabled: true,
    logLevel: "warning",
  },
  PARAM_DESCRIPTION_IDENTICAL_TO_DISPLAY_NAME: {
    lintAreas: ["paramDescription", "displayName"],
    lintIssue: "unneeded",
    message: "Param description identical to `displayName`",
    enabled: true,
    logLevel: "warning",
  },
  NON_STANDARD_HTML_LINE_BREAK: {
    lintAreas: ["paramDescription"],
    lintIssue: "unneeded",
    message: "Non-standard HTML element syntax for line break",
    enabled: true,
    logLevel: "info",
  },
};
